### PR TITLE
feat: add showNews method

### PR DESCRIPTION
**Pull request by stefanoCrmg**
Intercom has recently(?) added the `showNews` feature and I figured it might be worth it to map it 😄 https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshownews-newsitemid

I would have also added an e2e test for the feature but without having an actual `news` on the intercom instance it just didn't make much sense.

If you could please create a `news` on Intercom and provide the `newsId` I'll gladly write an E2E for it!

### CODE REVIEW

**Comment by devrnt** [comment]
This is great, big thanks! I've created a news item (33910172) and tested it but at the moment it doesn't work. I think this has to do with the fact that this feature is still in beta

**Comment by bel0v** [comment]
Hi! really looking forward to this feature. I wired it up it with
```
      window.Intercom.apply(null, ['showNews', id])
```
for now and it worked. Hoping to see it in `react-use-intercom`'s API!

**Comment by stefanoCrmg** [comment]
Yep, unfortunately it looks like I'll need a different ID to make the example work and not just show a white screen 🤔 
I reviewed my PR a bit as I had introduced an upgrade to pnpm.lock by error, the CI checks work fine now.

**Comment by stefanoCrmg** [comment]
@devrnt I've tried countless of time building this project in a docker container running `node@18.16.0` just like the github action but I can never get the build to fail.

Do you have any idea on what I should take a look at to get everything to work? I'm a bit lost 🤔

**Comment by devrnt** [comment]
The pipeline is working again. Still thinking about what to do with the news id in the examples

**Review by exah — APPROVED** [review]

**Comment by devrnt** [comment]
Later than expected but I decided to merge this PR even without a working example. I  still can't create a news item for the playground/demo namespace

**Comment by devrnt** [comment]
Big thanks!

**Pull request merged**
