### PR TITLE
feature: adding api_base option

### PR DESCRIPTION
**Pull request by doankhoi**

### CODE REVIEW

**Comment by devrnt** [comment]
Thanks for your PR. Can I ask why this dynamic `api_base` is needed? I did a search and did not find anything about this base url in the Intercom docs. Could you provide a link to your source?

**Comment by doankhoi** [comment]
This is a bug of Intercom, some Internet Service Providers in Vietnam are not connecting to Intercom. Intercom added `api_base` attribute to their config
Screen Shot 2020-09-28 at 11 49 22 PM

**Comment by devrnt** [comment]
I see, but I would like a url to some official documentation so I can confirm this. Could you add some tests to make sure there are no side effects?

**Comment by devrnt** [comment]
@doankhoi Have you got any update on this? Otherwise I'm inclined to close this PR.

**Comment by devrnt** [comment]
Saw another related issue for a simular Intercom solution: https://github.com/intercom/intercom-rails/pull/329/files

**Comment by musiquarc** [comment]
Hello ! Is this fix still up-to-date ? I tried to use the apiBase prop without success. It seems that the official API Doc has changed slightly, introducing a discrepancy between react-use-intercom, and Intercom. 

The documentation ( https://developers.intercom.com/installing-intercom/docs/basic-javascript ) gives 3 possible values for `api_base` : 

Regional Location | API Base to Set
US | https://api-iam.intercom.io
EU | https://api-iam.eu.intercom.io
Australia | https://api-iam.au.intercom.io

Hence I don't think the react-use-intercom feature is up-to-date. See current explanation about IntercomProvider's props `apiBase` :
"apiBase | If you need to route your Messenger requests through a different  endpoint than the default. Generally speaking, this is not needed. Format: https://${INTERCOM_APP_ID}.intercom-messenger.com"

I have tried both `https://api-iam.eu.intercom.io` and `https://${INTERCOM_APP_ID}.intercom-messenger.com` apiBase formats, without success.

To bypass that problem, I need to delete react-use-intercom and use the traditional HTML Intercom implementation.

Thanks !

**Comment by devrnt** [comment]
Hi, indeed the according documentation is outdated, but the functionality hasn't changed. You can still set the `apiBase` if required

**Comment by pradeepgill007** [comment]
It does not work for me as well.
I tried to implement it for EU | https://api-iam.eu.intercom.io/

Removing the react-use-intercom package from my project.

**Pull request merged**
