### PR TITLE
Add and implement snake-camel conversion functions

### LINKED ISSUE #16: Cannot use snake cased args (for non-custom Intercom props)
During migration from `react-intercom`, we ran into another little issue with variable names.  As described, all of Intercom's default props are camel cased, however there are implications that snake casing is allowed.  However, when I tried to pass `user_hash`, it apparently was not passed to Intercom.  It seems that in `mapDataAttributesToRawDataAttributes()`, `user_hash` is overwritten by whatever `userHash` is.

### PR DESCRIPTION
**Pull request by vinyldarkscratch**
Fixes #16 and #17.  This PR introduces two new functions that convert camel-cased keys to snake-cased in a given object, and vice versa.  A list of keys to convert can also be passed in, allowing for selective key conversion so that we are not affecting custom variables.  Furthermore, the functions are written to only affect existent keys, so that if we're converting from camel casing to snake casing, but `user_hash` is defined and `userHash` is not, it doesn't set the former to `undefined`.

Note: the tests are passing locally.  I'm not sure why they're failing here.

(P.S. for code clarity and to reduce the length of function names, I'd suggest renaming the mapping functions from `mapRawXXXToXXX` to `mapSnakeToCamelXXX`, and renaming "Raw" types to `SnakeXXX` and `CamelXXX`, where the `XXX` type is defined as `SnakeXXX | CamelXXX`.)

### CODE REVIEW

**Comment by vinyldarkscratch** [comment]
I don't know why Cypress is failing, since it's not failing locally...  Probably a fluke?

**Comment by devrnt** [comment]
I deliberately chose to use the mappers to have full control over my mapped attributes. This way it is more dev-friendly to maintain (if Intercom adds/removes any attributes). All "default" attributes that are listed [here](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects) should be camel case typed in `react-use-intercom`.
Also by using the functions `snakeToCamel` and `camelToSnake` we're losing our types.

In #16 `user_hash` should be used as `userHash` (because it is a "default" attribute, not a "custom attribute"). 

I'll update the docs to make this way of beviour much clearer.
[Default props](https://developers.intercom.com/installing-intercom/docs/javascript-api-attributes-objects) should be camel cased, custom attributes snake cased (for now).

**Comment by vinyldarkscratch** [comment]
Would you be willing to explain why this package is going for camel casing for the default props?  So far, I haven't seen any real benefits for camel casing, and with the issues in the mapping functions delaying our deployment featuring this package, I'm curious as to why.

> Also by using the functions `snakeToCamel` and `camelToSnake` we're losing our types.

Are you talking about some sort of TypeScript thing?  I'm not all that well-versed in TypeScript, I've only dabbled with it here and there.

**Comment by devrnt** [comment]
I've been troubled by the way we have to integrate Intercom in a React application. It was not how I wanted to write code, by pasting a snippet into the head tag, calling `window.Intercom`...
Conclusion some bad dev-experience for this specific use case: React Web application.

As far I know camel casing has been a naming convention in JavaScript for years. I peronsonally haven't seen any JavaScript source code that has been using any other than camel casing.

Because camel casing is somewhat a standardized naming convention I adopted it in `react-use-intercom`. This follows the convention and improves the developer experience.


Yes indeed, this is purely a TypeScript thing.

I'm planning to provide a `customAttributes` field in `boot` and `update` where you can pass your raw snake cased custom attributes.

**Pull request closed without merging**
