### PR TITLE
expose showTicket and showConversation

### PR DESCRIPTION
**Pull request by bananazigzags**
Exposes showTicket and showConversation methods in useIntercom hook

Closes https://github.com/devrnt/react-use-intercom/issues/670

### CODE REVIEW

**Comment by devrnt** [comment]
This is awesome big thanks!

**Review by devrnt — CHANGES_REQUESTED** [review]
Please run the linter

**Comment by bananazigzags** [comment]
> Please run the linter

For some reason, your lint:fix script didn't work for me. Tried passing --fix to "lint". Hope it worked fine

**Comment by bananazigzags** [comment]
Hi, do you have any pointers on how to fix the pipeline? I see a comment about one of the failing tests so it seems to be a recurring problem. No idea though why the other ones are failing.

**Comment by devrnt** [comment]
No idea to be honest, I'll have to look into it

**Comment by devrnt** [comment]
Should be resolved, sync with upstream please

**Comment by devrnt** [comment]
[5.4.0](https://github.com/devrnt/react-use-intercom/releases/tag/react-use-intercom%405.4.0)

**Pull request merged**
